a = float(input('a: '))
b = float(input('b: '))
print(a, '+', b, '=', a+b)
print(a, '-', b, '=', a-b)
print(a, '*', b, '=', a*b)
print(a, '/', b, '=', a/b)
print(a, '^', b, '=', a**b)
print('Остаток от деления', a, 'на', b, 'равен', int(a%b))
print('Целая часть от деления', a, 'на', b, 'равна', int(a//b))
